version: '3.4'

services:
  contactmanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;
      - ASPNETCORE_HTTP_PORTS=8080
      - AllowedCORSOrigins=${AllowedCORSOrigins}
      - UseCORS=${UseCORS}
      - ConnectionStrings__Db=${ConnectionStrings__Db}
      - EFCreateDatabase=${EFCreateDatabase}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  contactmanager.client:
    environment:
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    - ASPNETCORE_URLS=http://+:8080;
    - ASPNETCORE_HTTP_PORTS=8080
    - ApiUrl=${ApiUrl}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
